title: राधारमण कथा
description: श्री कार्तिक गोस्वामी जी महाराज कथा
author: श्री कार्तिक गोस्वामी जी महाराज
email: saurabhsikka@icloud.com
lang: en-us
copyright: "&#x2117; &amp; &#xA9; 2022"
logo: /assets/img/logo.png
url: "https://nacicatus.github.io" 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
