title: Mango Nectar
description: स्व्यंभू श्री राधारमण
author: Radha Raman
email: yajnavalkya@live.com
lang: en-us
copyright: "&#xA9; 2024"
logo: /assets/img/rr5.png
url: "https://nacicatus.github.io" 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
